<?php

use App\Models\AccountEntry;
use App\Models\Customer;
use App\Models\Delivery;
use App\Models\Enums\AccountEntryDirection;
use App\Models\Enums\AccountEntryType;
use App\Models\Enums\AccountEntryValidationStatus;
use App\Models\Enums\DeliveryOrderStatus;
use App\Models\Enums\DeliveryStatus;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class BackfillMissingChargesDelivery129 extends Migration
{
    const DELIVERY_ID = 129;

    /**
     * @return void
     */
    public function up()
    {
        DB::transaction(function () {
            $delivery = Delivery::with(['deliveryOrders.order'])->find(self::DELIVERY_ID);

            if (!$delivery) {
                echo "Backfill delivery 129: reparto no encontrado, se omite.\n";
                return;
            }

            if ($delivery->status !== DeliveryStatus::CLOSED) {
                echo "Backfill delivery 129: reparto no está cerrado (status={$delivery->status}), se omite.\n";
                return;
            }

            $occurredAt = $delivery->finished_at ?: now();
            $created = 0;
            $skippedExisting = 0;
            $skippedNotDelivered = 0;

            foreach ($delivery->deliveryOrders as $deliveryOrder) {
                if ($deliveryOrder->delivery_status !== DeliveryOrderStatus::DELIVERED) {
                    $skippedNotDelivered++;
                    continue;
                }

                $order = $deliveryOrder->order;
                if (!$order) {
                    continue;
                }

                if (AccountEntry::where('source_type', 'orders')
                    ->where('source_id', $order->id)
                    ->exists()) {
                    $skippedExisting++;
                    continue;
                }

                $customer = Customer::find($order->id_customer);
                $balanceAtEntry = $customer ? (float) $customer->current_balance : null;

                AccountEntry::create([
                    'customer_id' => $order->id_customer,
                    'type' => AccountEntryType::CHARGE,
                    'direction' => AccountEntryDirection::DEBIT,
                    'amount' => $order->total,
                    'occurred_at' => $occurredAt,
                    'notes' => 'Generated by script',
                    'source_type' => 'orders',
                    'source_id' => $order->id,
                    'created_by_user_id' => null,
                    'validation_status' => AccountEntryValidationStatus::VALIDATED,
                    'balance_at_entry' => $balanceAtEntry,
                ]);

                $created++;
            }

            echo "Backfill delivery 129: cargos creados={$created}, omitidos_existentes={$skippedExisting}, omitidos_no_delivered={$skippedNotDelivered}\n";
        });
    }

    /**
     * @return void
     */
    public function down()
    {
        // No se revierte: evita pérdida de datos de cuenta corriente.
    }
}
